#!/bin/ruby

require "peto"

require "net/http"
require "active_support"

$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), '..', 'contracts', 'generated'))
require "foo"
require "user"
require "animal"

host = ARGV[0]|| "localhost"
port = ARGV[1]|| 3000
Net::HTTP.version_1_2
Net::HTTP.start(host, port) do |http|
  query = Peto::Foo.set_user(Peto::User.new(:name=>"alice"))

  json = ActiveSupport::JSON.encode(query)
  request = Net::HTTP::Post.new("/foo")
  request["Accept"] = "application/json"
  request["Content-Type"] = "application/json"
  response = http.request(request, json)
  p response.body
  puts json
  p response
end

